[pkg.gnome]
description = "GNOME 3 session"
source = "gnome-session"

[pkg.gdebi]
source = "gdebi"

[pkg.terminal]
description = "GNOME 3 terminal"
source = "gnome-terminal"

[pkg.nemo]
source = "nemo"


[pkg.nautilus]
source = "nautilus"

[pkg.sushi]
description = "Quick previewer for nautilus"
source = "gnome-sushi"

[pkg.epub-thumb]
source = "gnome-epub-thumbnailer"

[pkg.nautilus-admin]
source = "nautilus-admin"

[pkg.nautilus-share]
source = "nautilus-share"

