[package]
name = "crusty"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = { version = "2.7.1", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"

[[bin]]
name="crusty"
path ="src/bin/crusty.rs"
